version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "yearly"
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "yearly"
